- name: Update all packages to the latest version
  apt:
    update_cache: yes
    cache_valid_time: 864000  # 86400 1 day
    upgrade: dist
    autoclean: yes
    autoremove: yes
    purge: yes
  become: true

- name: Reboot system if required
  command: shutdown -r now 'Rebooting to complete system upgrade'
  args:
    removes: /var/run/reboot-required
  become: true

